name: dotnet workflow

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: install dependencies
        run: dotnet restore ./facebookCodingPuzzles/Level1/Level1.csproj
      - name: build
        run: dotnet build ./facebookCodingPuzzles/Level1/Level1.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test ./facebookCodingPuzzles/Level1/Level1.csproj --no-restore --verbosity normal