name: dotnet workflow

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore ./Practice.csproj
      - name: Build
        run: dotnet build ./Practice.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test ./Practice.csproj --no-restore --verbosity normal